sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t kiran/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kiran/react-test npm test

after_success:
  - docker build -t kiran/multi-client ./client
  - docker build -t kiran/multi-nginx ./nginx
  - docker build -t kiran/multi-server ./server
  - docker build -t kiran/multi-worker ./worker

  #Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #push images to docker hub
  - docker push kiran/multi-client
  - docker push kiran/multi-nginx
  - docker push kiran/multi-server
  - docker push kiran/multi-worker